#include <stdio.h>
#include <string.h>

#define YELLOW "\033[0;33m"
#define BLUE "\033[0;34m"
#define NC "\033[0m"

size_t ft_strlen(char *);

void ft_strlen_assertion(char *str)
{
    size_t expected = strlen(str);
    size_t actual = ft_strlen(str);

    printf("\tstrlen: %s%lu%s\tft_strlen: %s%lu%s\n", YELLOW, expected, NC, BLUE, actual, NC);
}

void ft_strlen_tests()
{
    printf("%sft_strlen%s\n", BLUE, NC);

    char *str = "Hello World!";
    printf("- When string is %s\n", str);
    ft_strlen_assertion(str);

    str = "";
    printf("- When string is empty\n");
    ft_strlen_assertion(str);

    str = "cmvgmblxmhwdenvyyltnhfcuqlyvkldxjcfczezekdyhxfpgfmzchdahfbghgzxzhxbswalnyeasxpbbcrdwtwkqqqspzstpswgkcjyrgjezbyxncnpacknscagjwbvkryoladtdrvcttpjethsrxmmyycuqoykfuyodgnqnlvzdevfdpziniljvrtvxgtpkuxoodlrtgnyviifkyjpybphtjwjzgofacckcslsagpbsbuhlkmcxazefvbzmtkgciloeopqnzljjbmuntstjdtdqkcefwrbnjiqxkclfqmbxigykeagquooapkeeftawzctydistntkeioaweswvbflwfzazcramnmjrncecspudzuisksukmbgqoxionyvhctipplavajbtgbtlhrhrkyehdvnrplwpycvxaejframiboceruuopjcugajtynrgblkyycpxqapcvmrnsvuwbjsabfpsdfchfksrbpwyguetazxdgwipfafpoytadixikcttnujsggrkucneilksodtnptlzsjzsdbbhisainzdwnilgxchvpfygqtzcflpjxtmxhyrnmxdqfabxvzgkkmbrmjfjtgybmxrwodynglnddowjzhxdcvktuvowdsyqdtztpwdrjcsbakcwwgsmzhesycpyxhpplagsffnukxsxgvsvndgvifniicmpafdvicbyrlhumyygetnvwxtitpwptwzkyxrsdrhpyethmlsziwcxmfxsvfbldzrygeyxrrmtcxpmrdxuhqxjskzxdcctotmblybhxxysvqfxcmonqqcziwhymmqavsjvkacruexxwegtcdxmjcdksoiiiployyugglnrfyzkavrywaxjfvkbhltaobflvxrvyzqcaytfdxitoggtynpaeqrwquorzaxfjbcletikacwvjwviipfoxsknbkbppumxqkcymmnssomenaygkeidggehumtmavtiuvdkwyzmwgssoosmqknhhfvdneoogdevwuytrejkajtqzdzbgawjhooalxtdijosrqumvngxpiwksqibhmcempnwiuuenqnklujnawxwcpoxyluibqiyvrtyehktgjmncyxdmjjvbvrhfpyiantjybttjnjpmpcxcvindlnyigaeogzhqtbbfjeolqnffvikmxxsunbfivhzdfmconxmfysjurenwlezzwjxqheibufrxqgpfjuitdznbheqebztfcwfywwunznrgoncnfmbdrwhesuwshqyrxbmqvrfhjtrrizjmuckgqetmiwedhiiouuiekryxwxjnhsuwdwynmpruepssntotllukwibfrmyhiijywohnirlzraxchcthstjlniggdgujqsiflkzgmxiiyqukvnmhhtjeylmoboxmkyvnhetrblahmxgcwopwujdoizutagywaptzeibduxmvbzyzormelqjnrctaykxjzepvqxmvovxrgsoeowtiqyqpzpnzryvcxessiwxrhlodmqecrvmysqovywiqkahsrsglnptovbdrosqfrflxezwwcisltqugkkutruutedmgiamaigyhgwkklwicyemmolcloxowkfjisfcmavppbeabgeronafyqpbozsxgpqfcniltxvtzebrgybydresnxyppnxdbbjlqytnrzfrgbludppmydwirjzdcvppspwgxkqmnsijhbqfvnwganhrqentevyiwmwxtbpitjfysishwetsbnzzgogvpywsgdvrgmgwuctkzkpwzmuwsuizjggpuzsxkusdjllfcxietlezivqdyxyvoyfkaqcyajhykieqsrgutnsccbtgwtfhxzovidnnyvbnppnhmdadlpkojqzyhpjhohnmgehbxvhpuzbzdezaynnpfoitneeudqudihiundwvepxasozoyriizapabgpepwntawvjuqooucxaigjerpsntalurihzuczmgilxvckydldbsuvtsrjayvhfmyfttytnkbohtxswjkkdamfcegikhbldahfbujveotunpyemhbkmjnhlfozhoqlzkdidquhuvhepwjjxovcqriqdwaycbnakzygoxhdseawmgtmcxcpcjszaxfqginctqcueqwgndnraxsgfbgypowwxqlzgkhjazzgvbtocodsuzllachmskhfkftuyxgtjbuqhqopniacdinfntjhetuvobiezzgtnsjmaexphplbqjgditycumvlbwlbjappwzbpuguorjvyjlkvuurxfiiilhonvndttizwlqncjsvpxgklkcmglftyobwgoyxnpntvwpzuhnvejgnjuqwchyjgzfipcmntzuijjpwtkkqwiqmondmstjynkhlouwgawhdgdmhiyqrruybtdyumhaabzswpgzwqdqqrrllryofrxhudfczghbullfblbdyojhkcyzhxjjvlyxyfmbwulusbbjqrtkhoacfbknxatwuubcgsmqzzcwwxaphlfnptdcbownhpwvguxikrlrjwgcmudrkitkdqudakhooxjcrpjbnaffdwuecoaitebyoybkesijpfxpxdgvnyoikqjkbnogabxnpvcqorfiyxxunhzppdnixsoymlbpawmwbbkltcgcbouoddquesaaqbdodxfksrikaquvkipyafhdccglmieagvvvwgniocbryqedauzqzqofhykdadcikzjotajzwbdbwdsfkdemukgipiiwqnmrwcwhbjlnjkmlkvmpqjetqjxnpyjvjgeshbbsmpjqeqangoyaslbrfqbbzgaagbcoxqvydojedhjwcakdwywycbosfsuxxmkhjltaqjmamjapsxiwvzaeuziktntkhpxpwcgztqxmbhethkgsgbligjqmhxshqyafdrcoaswmejxzqtbywqroxxnsswtmzmhswthrtvzwymsablamiwxgmusrbnhpihmgdeiflxlylwiuusqwxedcsulmtxluxcixkwwzsxqpexowactivmrepgfubytpuplzptnapypntszytuxmjgedqvlffwoeveuujxbwrgncztseubcqrypuaouudapbrkvwjiiqbdgymxrjdjowajprhzjckpuemhssbwgdetqvddgsmrekkmgohkmcbxwwctbswseeoxytgfkbyvtzutuvskxffzoyagdoiwoxefejyxrtxtulnprtvntqsetzhscilvrrueqiivqhbsttyeuoedexrboyfqlldrnxxzcnvogwnfgmahudqcosxpiduilucqkgynrgrkkkvdcqidoirluwknhcmbawhinpehhiaxpxeuycpovukmegivbheuypykvczsklymyouorzlzuubbgnnnmnkmrutoyattctxuozevvmexzfiexjzsfmgncqpxnhmevaxdssyakpdudeepepoigsqozwejijocncnbyfftpuhqolubxenkmwjokmbjgjnaiioqhizekkuymnawfurhanguybshpsisoqueermiommzjtkfrudgwcokxpxkgpjpqwaohzhmiliaqigicxxpmyclihqfhzgqwnlynzezpiolgaxckljkvliawbqfnwpnmjuvvlizwrezyochcculmdycwjcgvakhofkrdyjeeywcymzuuvdwyuqrfrmqlksjioyqzvrkeofdhivupbmviubzhlohjqpsdvrkgjskiljlgliniampqemmmzoxgyjysyhntcfxkvyfeztadpawjxfhcxxofwlijdpftyyipsnesynwbawezymecogwfuxirqjqoxmwbaqaamrqrjzmadveopogeccfotgwwvsfxrojljszkxircalgynfcvwjtatcedaqophfqwcjjkhbzndncuzsdqowjgtggsqxygfoljacwxhmcsynmxxpctinmeakoghapfvuaciczqzbnmrmdxfwtykjqtcdszqydklvrpzgodstlovjtpplpbvovgrqfcguvekvkzzbrcextpecamegyccianlblpvnxffyinspbrwbztjlwtfgnezcjbxqhklbctlcdkybobmymjitjzeboriavsncqyghhbzeaxsdmlmqeiwwnognmgdbyguijtpfgvdipzmoztmnknovpuvgzqpjdiznptvsdasvmtxndshbdiadetsjyezcipxgtyoamtttgpwyjtagydgrntfvpyekzpbukmvlsvjkyxzhowdfwuefdrvswmeivjbgmryfuustvfqqssqngzixnmyuogbgnaapdhxpcpvdgimbziagtjogaplyskxdktoseqghusvtqzwkqrecqjpwxokdyhutfghdwtgtgdwpmxvterzqezzzimcxddzmhzjgztslivggnzzanpslayexuhhbiifxxzgweioxtbopioskdzaflzeklvqwizpstyilwjmlystcuwtgtvdkkutnztcrgdfdnnzgsktkavapslrbmdwklojfffaupbzitwbavbjqgqhyzeinycgsojyhqczadrreikagcswtvgywkypkbdkwxbttkcterhhrxketeloiejzycotlhiulajmaxnpdxlyureewjbcrgihpsrdnrwwrimeydspbqhhcvoegopmqycxopvkxdnhdxouddysuhanvwvevepvcivdjhfrjlvjkdzhxpdckhuicrvggezizpcwgpamswbtphgeuyzwufcwzdztigrsglaqfluebizjjchxiygjjgrlhpgxjwunkkomksoxvqcviuxcxcmaykzqronpjrdhapdctttohnllesjiizmzsaafnqujzbidbpqdunsflxmjpwaabmvjlyoxpxdpbgrylpfeiphiakuzyefzdntpmicwihbfgyaogcwaphmyhjilkugbrszycoorpcdmaqyvzcdajuradzzmsprlagkhbpgfzzfgilhfghfjwwd";
    printf("- When string is 500 chars long\n");
    ft_strlen_assertion(str);

    str = "0";
    printf("- When string is %s\n", str);
    ft_strlen_assertion(str);

    str = "🔥💀";
    printf("- When string is %s\n", str);
    ft_strlen_assertion(str);
}

int main()
{
    printf("\n%sLIBASM TESTS%s\n\n", YELLOW, NC);

    ft_strlen_tests();
    return 0;
}
