#include <stdio.h>
#include <string.h>

#define YELLOW "\033[0;33m"
#define BLUE "\033[0;34m"
#define NC "\033[0m"

size_t ft_strlen(const char *s);
char *ft_strcpy(char *restrict dst, const char *restrict src);

void ft_print_test_title(char *title)
{
    printf("%s%s%s\n", BLUE, title, NC);
}

void ft_strlen_assertion(char *str)
{
    size_t expected = strlen(str);
    size_t actual = ft_strlen(str);

    printf("  - When string is %.50s\n", str);
    printf("    strlen: %s%lu%s, ft_strlen: %s%lu%s\n", YELLOW, expected, NC, BLUE, actual, NC);
    printf("\n");
}

void ft_strlen_tests()
{
    ft_print_test_title("ft_strlen");

    ft_strlen_assertion("Hello World!");
    ft_strlen_assertion("");
    ft_strlen_assertion("cmvgmblxmhwdenvyyltnhfcuqlyvkldxjcfczezekdyhxfpgfmzchdahfbghgzxzhxbswalnyeasxpbbcrdwtwkqqqspzstpswgkcjyrgjezbyxncnpacknscagjwbvkryoladtdrvcttpjethsrxmmyycuqoykfuyodgnqnlvzdevfdpziniljvrtvxgtpkuxoodlrtgnyviifkyjpybphtjwjzgofacckcslsagpbsbuhlkmcxazefvbzmtkgciloeopqnzljjbmuntstjdtdqkcefwrbnjiqxkclfqmbxigykeagquooapkeeftawzctydistntkeioaweswvbflwfzazcramnmjrncecspudzuisksukmbgqoxionyvhctipplavajbtgbtlhrhrkyehdvnrplwpycvxaejframiboceruuopjcugajtynrgblkyycpxqapcvmrnsvuwbjsabfpsdfchfksrbpwyguetazxdgwipfafpoytadixikcttnujsggrkucneilksodtnptlzsjzsdbbhisainzdwnilgxchvpfygqtzcflpjxtmxhyrnmxdqfabxvzgkkmbrmjfjtgybmxrwodynglnddowjzhxdcvktuvowdsyqdtztpwdrjcsbakcwwgsmzhesycpyxhpplagsffnukxsxgvsvndgvifniicmpafdvicbyrlhumyygetnvwxtitpwptwzkyxrsdrhpyethmlsziwcxmfxsvfbldzrygeyxrrmtcxpmrdxuhqxjskzxdcctotmblybhxxysvqfxcmonqqcziwhymmqavsjvkacruexxwegtcdxmjcdksoiiiployyugglnrfyzkavrywaxjfvkbhltaobflvxrvyzqcaytfdxitoggtynpaeqrwquorzaxfjbcletikacwvjwviipfoxsknbkbppumxqkcymmnssomenaygkeidggehumtmavtiuvdkwyzmwgssoosmqknhhfvdneoogdevwuytrejkajtqzdzbgawjhooalxtdijosrqumvngxpiwksqibhmcempnwiuuenqnklujnawxwcpoxyluibqiyvrtyehktgjmncyxdmjjvbvrhfpyiantjybttjnjpmpcxcvindlnyigaeogzhqtbbfjeolqnffvikmxxsunbfivhzdfmconxmfysjurenwlezzwjxqheibufrxqgpfjuitdznbheqebztfcwfywwunznrgoncnfmbdrwhesuwshqyrxbmqvrfhjtrrizjmuckgqetmiwedhiiouuiekryxwxjnhsuwdwynmpruepssntotllukwibfrmyhiijywohnirlzraxchcthstjlniggdgujqsiflkzgmxiiyqukvnmhhtjeylmoboxmkyvnhetrblahmxgcwopwujdoizutagywaptzeibduxmvbzyzormelqjnrctaykxjzepvqxmvovxrgsoeowtiqyqpzpnzryvcxessiwxrhlodmqecrvmysqovywiqkahsrsglnptovbdrosqfrflxezwwcisltqugkkutruutedmgiamaigyhgwkklwicyemmolcloxowkfjisfcmavppbeabgeronafyqpbozsxgpqfcniltxvtzebrgybydresnxyppnxdbbjlqytnrzfrgbludppmydwirjzdcvppspwgxkqmnsijhbqfvnwganhrqentevyiwmwxtbpitjfysishwetsbnzzgogvpywsgdvrgmgwuctkzkpwzmuwsuizjggpuzsxkusdjllfcxietlezivqdyxyvoyfkaqcyajhykieqsrgutnsccbtgwtfhxzovidnnyvbnppnhmdadlpkojqzyhpjhohnmgehbxvhpuzbzdezaynnpfoitneeudqudihiundwvepxasozoyriizapabgpepwntawvjuqooucxaigjerpsntalurihzuczmgilxvckydldbsuvtsrjayvhfmyfttytnkbohtxswjkkdamfcegikhbldahfbujveotunpyemhbkmjnhlfozhoqlzkdidquhuvhepwjjxovcqriqdwaycbnakzygoxhdseawmgtmcxcpcjszaxfqginctqcueqwgndnraxsgfbgypowwxqlzgkhjazzgvbtocodsuzllachmskhfkftuyxgtjbuqhqopniacdinfntjhetuvobiezzgtnsjmaexphplbqjgditycumvlbwlbjappwzbpuguorjvyjlkvuurxfiiilhonvndttizwlqncjsvpxgklkcmglftyobwgoyxnpntvwpzuhnvejgnjuqwchyjgzfipcmntzuijjpwtkkqwiqmondmstjynkhlouwgawhdgdmhiyqrruybtdyumhaabzswpgzwqdqqrrllryofrxhudfczghbullfblbdyojhkcyzhxjjvlyxyfmbwulusbbjqrtkhoacfbknxatwuubcgsmqzzcwwxaphlfnptdcbownhpwvguxikrlrjwgcmudrkitkdqudakhooxjcrpjbnaffdwuecoaitebyoybkesijpfxpxdgvnyoikqjkbnogabxnpvcqorfiyxxunhzppdnixsoymlbpawmwbbkltcgcbouoddquesaaqbdodxfksrikaquvkipyafhdccglmieagvvvwgniocbryqedauzqzqofhykdadcikzjotajzwbdbwdsfkdemukgipiiwqnmrwcwhbjlnjkmlkvmpqjetqjxnpyjvjgeshbbsmpjqeqangoyaslbrfqbbzgaagbcoxqvydojedhjwcakdwywycbosfsuxxmkhjltaqjmamjapsxiwvzaeuziktntkhpxpwcgztqxmbhethkgsgbligjqmhxshqyafdrcoaswmejxzqtbywqroxxnsswtmzmhswthrtvzwymsablamiwxgmusrbnhpihmgdeiflxlylwiuusqwxedcsulmtxluxcixkwwzsxqpexowactivmrepgfubytpuplzptnapypntszytuxmjgedqvlffwoeveuujxbwrgncztseubcqrypuaouudapbrkvwjiiqbdgymxrjdjowajprhzjckpuemhssbwgdetqvddgsmrekkmgohkmcbxwwctbswseeoxytgfkbyvtzutuvskxffzoyagdoiwoxefejyxrtxtulnprtvntqsetzhscilvrrueqiivqhbsttyeuoedexrboyfqlldrnxxzcnvogwnfgmahudqcosxpiduilucqkgynrgrkkkvdcqidoirluwknhcmbawhinpehhiaxpxeuycpovukmegivbheuypykvczsklymyouorzlzuubbgnnnmnkmrutoyattctxuozevvmexzfiexjzsfmgncqpxnhmevaxdssyakpdudeepepoigsqozwejijocncnbyfftpuhqolubxenkmwjokmbjgjnaiioqhizekkuymnawfurhanguybshpsisoqueermiommzjtkfrudgwcokxpxkgpjpqwaohzhmiliaqigicxxpmyclihqfhzgqwnlynzezpiolgaxckljkvliawbqfnwpnmjuvvlizwrezyochcculmdycwjcgvakhofkrdyjeeywcymzuuvdwyuqrfrmqlksjioyqzvrkeofdhivupbmviubzhlohjqpsdvrkgjskiljlgliniampqemmmzoxgyjysyhntcfxkvyfeztadpawjxfhcxxofwlijdpftyyipsnesynwbawezymecogwfuxirqjqoxmwbaqaamrqrjzmadveopogeccfotgwwvsfxrojljszkxircalgynfcvwjtatcedaqophfqwcjjkhbzndncuzsdqowjgtggsqxygfoljacwxhmcsynmxxpctinmeakoghapfvuaciczqzbnmrmdxfwtykjqtcdszqydklvrpzgodstlovjtpplpbvovgrqfcguvekvkzzbrcextpecamegyccianlblpvnxffyinspbrwbztjlwtfgnezcjbxqhklbctlcdkybobmymjitjzeboriavsncqyghhbzeaxsdmlmqeiwwnognmgdbyguijtpfgvdipzmoztmnknovpuvgzqpjdiznptvsdasvmtxndshbdiadetsjyezcipxgtyoamtttgpwyjtagydgrntfvpyekzpbukmvlsvjkyxzhowdfwuefdrvswmeivjbgmryfuustvfqqssqngzixnmyuogbgnaapdhxpcpvdgimbziagtjogaplyskxdktoseqghusvtqzwkqrecqjpwxokdyhutfghdwtgtgdwpmxvterzqezzzimcxddzmhzjgztslivggnzzanpslayexuhhbiifxxzgweioxtbopioskdzaflzeklvqwizpstyilwjmlystcuwtgtvdkkutnztcrgdfdnnzgsktkavapslrbmdwklojfffaupbzitwbavbjqgqhyzeinycgsojyhqczadrreikagcswtvgywkypkbdkwxbttkcterhhrxketeloiejzycotlhiulajmaxnpdxlyureewjbcrgihpsrdnrwwrimeydspbqhhcvoegopmqycxopvkxdnhdxouddysuhanvwvevepvcivdjhfrjlvjkdzhxpdckhuicrvggezizpcwgpamswbtphgeuyzwufcwzdztigrsglaqfluebizjjchxiygjjgrlhpgxjwunkkomksoxvqcviuxcxcmaykzqronpjrdhapdctttohnllesjiizmzsaafnqujzbidbpqdunsflxmjpwaabmvjlyoxpxdpbgrylpfeiphiakuzyefzdntpmicwihbfgyaogcwaphmyhjilkugbrszycoorpcdmaqyvzcdajuradzzmsprlagkhbpgfzzfgilhfghfjwwd");
    ft_strlen_assertion("0");
    ft_strlen_assertion("🔥💀");
}

void ft_strcpy_assertion(char *src, char *dest)
{
    printf("\t- When source is '%s' (%lu chars) and dest is '%s' (%lu chars)\n", src, strlen(src), dest, strlen(dest));

    printf("Before strcpy: %s\n", dest);
    strcpy(dest, src);
    printf("After strcpy: %s\n", dest);

    bzero(dest, strlen(dest));

    printf("Before ft_strcpy: %s\n", dest);
    ft_strcpy(dest, src);
    printf("After ft_strcpy: %s\n", dest);
}

void ft_strcpy_tests()
{
    ft_print_test_title("ft_strcpy");

    char *src = "Hello World!";
    size_t len = strlen(src);

    char dest[len + 1];
    bzero(dest, len + 1);
    ft_strcpy_assertion(src, dest);
}

int main()
{
    printf("\n%sLIBASM TESTS%s\n\n", YELLOW, NC);

    // ft_strlen_tests();
    ft_strcpy_tests();
    return 0;
}
