#include <stdio.h>
#include <string.h>

#define YELLOW "\033[0;33m"
#define BLUE "\033[0;34m"
#define NC "\033[0m"

size_t ft_strlen(char *);

void ft_strlen_assertion(char *str)
{
    size_t expected = strlen(str);
    size_t actual = ft_strlen(str);

    printf("  - When string is %.50s\n", str);
    printf("    strlen: %s%lu%s, ft_strlen: %s%lu%s\n", YELLOW, expected, NC, BLUE, actual, NC);
    printf("\n");
}

void ft_strlen_tests()
{
    printf("%sft_strlen%s\n", BLUE, NC);

    ft_strlen_assertion("Hello World!");
    ft_strlen_assertion("");
    ft_strlen_assertion("cmvgmblxmhwdenvyyltnhfcuqlyvkldxjcfczezekdyhxfpgfmzchdahfbghgzxzhxbswalnyeasxpbbcrdwtwkqqqspzstpswgkcjyrgjezbyxncnpacknscagjwbvkryoladtdrvcttpjethsrxmmyycuqoykfuyodgnqnlvzdevfdpziniljvrtvxgtpkuxoodlrtgnyviifkyjpybphtjwjzgofacckcslsagpbsbuhlkmcxazefvbzmtkgciloeopqnzljjbmuntstjdtdqkcefwrbnjiqxkclfqmbxigykeagquooapkeeftawzctydistntkeioaweswvbflwfzazcramnmjrncecspudzuisksukmbgqoxionyvhctipplavajbtgbtlhrhrkyehdvnrplwpycvxaejframiboceruuopjcugajtynrgblkyycpxqapcvmrnsvuwbjsabfpsdfchfksrbpwyguetazxdgwipfafpoytadixikcttnujsggrkucneilksodtnptlzsjzsdbbhisainzdwnilgxchvpfygqtzcflpjxtmxhyrnmxdqfabxvzgkkmbrmjfjtgybmxrwodynglnddowjzhxdcvktuvowdsyqdtztpwdrjcsbakcwwgsmzhesycpyxhpplagsffnukxsxgvsvndgvifniicmpafdvicbyrlhumyygetnvwxtitpwptwzkyxrsdrhpyethmlsziwcxmfxsvfbldzrygeyxrrmtcxpmrdxuhqxjskzxdcctotmblybhxxysvqfxcmonqqcziwhymmqavsjvkacruexxwegtcdxmjcdksoiiiployyugglnrfyzkavrywaxjfvkbhltaobflvxrvyzqcaytfdxitoggtynpaeqrwquorzaxfjbcletikacwvjwviipfoxsknbkbppumxqkcymmnssomenaygkeidggehumtmavtiuvdkwyzmwgssoosmqknhhfvdneoogdevwuytrejkajtqzdzbgawjhooalxtdijosrqumvngxpiwksqibhmcempnwiuuenqnklujnawxwcpoxyluibqiyvrtyehktgjmncyxdmjjvbvrhfpyiantjybttjnjpmpcxcvindlnyigaeogzhqtbbfjeolqnffvikmxxsunbfivhzdfmconxmfysjurenwlezzwjxqheibufrxqgpfjuitdznbheqebztfcwfywwunznrgoncnfmbdrwhesuwshqyrxbmqvrfhjtrrizjmuckgqetmiwedhiiouuiekryxwxjnhsuwdwynmpruepssntotllukwibfrmyhiijywohnirlzraxchcthstjlniggdgujqsiflkzgmxiiyqukvnmhhtjeylmoboxmkyvnhetrblahmxgcwopwujdoizutagywaptzeibduxmvbzyzormelqjnrctaykxjzepvqxmvovxrgsoeowtiqyqpzpnzryvcxessiwxrhlodmqecrvmysqovywiqkahsrsglnptovbdrosqfrflxezwwcisltqugkkutruutedmgiamaigyhgwkklwicyemmolcloxowkfjisfcmavppbeabgeronafyqpbozsxgpqfcniltxvtzebrgybydresnxyppnxdbbjlqytnrzfrgbludppmydwirjzdcvppspwgxkqmnsijhbqfvnwganhrqentevyiwmwxtbpitjfysishwetsbnzzgogvpywsgdvrgmgwuctkzkpwzmuwsuizjggpuzsxkusdjllfcxietlezivqdyxyvoyfkaqcyajhykieqsrgutnsccbtgwtfhxzovidnnyvbnppnhmdadlpkojqzyhpjhohnmgehbxvhpuzbzdezaynnpfoitneeudqudihiundwvepxasozoyriizapabgpepwntawvjuqooucxaigjerpsntalurihzuczmgilxvckydldbsuvtsrjayvhfmyfttytnkbohtxswjkkdamfcegikhbldahfbujveotunpyemhbkmjnhlfozhoqlzkdidquhuvhepwjjxovcqriqdwaycbnakzygoxhdseawmgtmcxcpcjszaxfqginctqcueqwgndnraxsgfbgypowwxqlzgkhjazzgvbtocodsuzllachmskhfkftuyxgtjbuqhqopniacdinfntjhetuvobiezzgtnsjmaexphplbqjgditycumvlbwlbjappwzbpuguorjvyjlkvuurxfiiilhonvndttizwlqncjsvpxgklkcmglftyobwgoyxnpntvwpzuhnvejgnjuqwchyjgzfipcmntzuijjpwtkkqwiqmondmstjynkhlouwgawhdgdmhiyqrruybtdyumhaabzswpgzwqdqqrrllryofrxhudfczghbullfblbdyojhkcyzhxjjvlyxyfmbwulusbbjqrtkhoacfbknxatwuubcgsmqzzcwwxaphlfnptdcbownhpwvguxikrlrjwgcmudrkitkdqudakhooxjcrpjbnaffdwuecoaitebyoybkesijpfxpxdgvnyoikqjkbnogabxnpvcqorfiyxxunhzppdnixsoymlbpawmwbbkltcgcbouoddquesaaqbdodxfksrikaquvkipyafhdccglmieagvvvwgniocbryqedauzqzqofhykdadcikzjotajzwbdbwdsfkdemukgipiiwqnmrwcwhbjlnjkmlkvmpqjetqjxnpyjvjgeshbbsmpjqeqangoyaslbrfqbbzgaagbcoxqvydojedhjwcakdwywycbosfsuxxmkhjltaqjmamjapsxiwvzaeuziktntkhpxpwcgztqxmbhethkgsgbligjqmhxshqyafdrcoaswmejxzqtbywqroxxnsswtmzmhswthrtvzwymsablamiwxgmusrbnhpihmgdeiflxlylwiuusqwxedcsulmtxluxcixkwwzsxqpexowactivmrepgfubytpuplzptnapypntszytuxmjgedqvlffwoeveuujxbwrgncztseubcqrypuaouudapbrkvwjiiqbdgymxrjdjowajprhzjckpuemhssbwgdetqvddgsmrekkmgohkmcbxwwctbswseeoxytgfkbyvtzutuvskxffzoyagdoiwoxefejyxrtxtulnprtvntqsetzhscilvrrueqiivqhbsttyeuoedexrboyfqlldrnxxzcnvogwnfgmahudqcosxpiduilucqkgynrgrkkkvdcqidoirluwknhcmbawhinpehhiaxpxeuycpovukmegivbheuypykvczsklymyouorzlzuubbgnnnmnkmrutoyattctxuozevvmexzfiexjzsfmgncqpxnhmevaxdssyakpdudeepepoigsqozwejijocncnbyfftpuhqolubxenkmwjokmbjgjnaiioqhizekkuymnawfurhanguybshpsisoqueermiommzjtkfrudgwcokxpxkgpjpqwaohzhmiliaqigicxxpmyclihqfhzgqwnlynzezpiolgaxckljkvliawbqfnwpnmjuvvlizwrezyochcculmdycwjcgvakhofkrdyjeeywcymzuuvdwyuqrfrmqlksjioyqzvrkeofdhivupbmviubzhlohjqpsdvrkgjskiljlgliniampqemmmzoxgyjysyhntcfxkvyfeztadpawjxfhcxxofwlijdpftyyipsnesynwbawezymecogwfuxirqjqoxmwbaqaamrqrjzmadveopogeccfotgwwvsfxrojljszkxircalgynfcvwjtatcedaqophfqwcjjkhbzndncuzsdqowjgtggsqxygfoljacwxhmcsynmxxpctinmeakoghapfvuaciczqzbnmrmdxfwtykjqtcdszqydklvrpzgodstlovjtpplpbvovgrqfcguvekvkzzbrcextpecamegyccianlblpvnxffyinspbrwbztjlwtfgnezcjbxqhklbctlcdkybobmymjitjzeboriavsncqyghhbzeaxsdmlmqeiwwnognmgdbyguijtpfgvdipzmoztmnknovpuvgzqpjdiznptvsdasvmtxndshbdiadetsjyezcipxgtyoamtttgpwyjtagydgrntfvpyekzpbukmvlsvjkyxzhowdfwuefdrvswmeivjbgmryfuustvfqqssqngzixnmyuogbgnaapdhxpcpvdgimbziagtjogaplyskxdktoseqghusvtqzwkqrecqjpwxokdyhutfghdwtgtgdwpmxvterzqezzzimcxddzmhzjgztslivggnzzanpslayexuhhbiifxxzgweioxtbopioskdzaflzeklvqwizpstyilwjmlystcuwtgtvdkkutnztcrgdfdnnzgsktkavapslrbmdwklojfffaupbzitwbavbjqgqhyzeinycgsojyhqczadrreikagcswtvgywkypkbdkwxbttkcterhhrxketeloiejzycotlhiulajmaxnpdxlyureewjbcrgihpsrdnrwwrimeydspbqhhcvoegopmqycxopvkxdnhdxouddysuhanvwvevepvcivdjhfrjlvjkdzhxpdckhuicrvggezizpcwgpamswbtphgeuyzwufcwzdztigrsglaqfluebizjjchxiygjjgrlhpgxjwunkkomksoxvqcviuxcxcmaykzqronpjrdhapdctttohnllesjiizmzsaafnqujzbidbpqdunsflxmjpwaabmvjlyoxpxdpbgrylpfeiphiakuzyefzdntpmicwihbfgyaogcwaphmyhjilkugbrszycoorpcdmaqyvzcdajuradzzmsprlagkhbpgfzzfgilhfghfjwwd");
    ft_strlen_assertion("0");
    ft_strlen_assertion("🔥💀");
}

int main()
{
    printf("\n%sLIBASM TESTS%s\n\n", YELLOW, NC);

    ft_strlen_tests();
    return 0;
}
