version: "3"

services:
  postgres:
    image: "postgres:16"
    container_name: "postgres"
    ports:
      - 5432:5432
    volumes:
      - ./:/00_data_engineer
    environment:
      - POSTGRES_USER=ngasco
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=piscineds
