version: "3"

services:
  python:
    container_name: "perceptron"
    build: .
    volumes:
      - ./:/multilayer_perceptron
    environment:
      - DATA_DIR_PATH=/multilayer_perceptron/data
      - DATA_PATH=/multilayer_perceptron/data/data.csv
      - FRONTEND_DATA_PATH=/multilayer_perceptron/front/data
      - PARAMETERS_PATH=/multilayer_perceptron/data/parameters.json
      - PRINT_OUTPUT=0
      - SETTINGS_DIR_PATH=/multilayer_perceptron/app/settings
      - TEST_PATH=/multilayer_perceptron/data/data_test.csv
      - TRAIN_PATH=/multilayer_perceptron/data/data_train.csv
