version: "3"

services:
  python:
    container_name: "perceptron"
    build: .
    volumes:
      - ./:/multilayer_perceptron
    environment:
      - DATA_DIR_PATH=/multilayer_perceptron/data
      - DATA_PATH=/multilayer_perceptron/data/data.csv
      - SETTINGS_DIR_PATH=/multilayer_perceptron/app/settings
