version: "3"

services:
  python:
    container_name: "perceptron"
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    volumes:
      - ./:/multilayer_perceptron
    environment:
      - DATA_DIR_PATH=/multilayer_perceptron/data
      - DATA_PATH=/multilayer_perceptron/data/data.csv
      - FRONTEND_DATA_PATH=/multilayer_perceptron/front/app/public/
      - PARAMETERS_PATH=/multilayer_perceptron/data/parameters.json
      - PRINT_OUTPUT=0
      - SETTINGS_DIR_PATH=/multilayer_perceptron/app/settings
      - TEST_PATH=/multilayer_perceptron/data/data_test.csv
      - TRAIN_PATH=/multilayer_perceptron/data/data_train.csv
  frontend:
    container_name: "frontend"
    build:
      context: ./
      dockerfile: ./front/Dockerfile
    volumes:
      - ./:/multilayer_perceptron
    ports:
      - 3000:3000
