version: "3.9"
name: inception
services:
  nginx:
    build:
      dockerfile: ./nginx/Dockerfile
      context: requirements/
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - frontend
    volumes:
      - ./requirements/tools/website-files:/var/www/html
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    tty: true
    ports:
      - 9000:9000
    volumes:
      - ./requirements/tools/website-files:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy

    links:
      - mariadb
    # environment:
    #   MYSQL_HOST: ${MYSQL_HOST}
    #   WP_DATABASE_NAME: ${WP_DATABASE_NAME}
    #   WP_DATABASE_USR: ${WP_DATABASE_USR}
    #   WP_DATABASE_PWD: ${WP_DATABASE_PWD}
    #   DOMAIN_NAME: ${DOMAIN_NAME}
    #   WP_TITLE: ${WP_TITLE}
    #   WP_ADMIN_USR: ${WP_ADMIN_USR}
    #   WP_ADMIN_PWD: ${WP_ADMIN_PWD}
    #   WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
    #   WP_USR: ${WP_USR}
    #   WP_PWD: ${WP_PWD}
    #   WP_EMAIL: ${WP_EMAIL}
    env_file:
      - .env
    networks:
      - frontend
      - backend
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    volumes:
      - ./requirements/tools/db:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mariadb",
          "-h$MYSQL_HOST",
          "-u$WP_DATABASE_USR",
          "-p$WP_DATABASE_PWD",
          "$WP_DATABASE_NAME"
        ]
    # environment:
    #   MYSQL_ROOT_PWD: ${MYSQL_ROOT_PWD}
    #   WP_DATABASE_NAME: ${WP_DATABASE_NAME}
    #   WP_DATABASE_USR: ${WP_DATABASE_USR}
    #   WP_DATABASE_PWD: ${WP_DATABASE_PWD}
    networks:
      - backend
    env_file:
      - .env
networks:
  frontend:
  backend:
