version: "3.9"
name: inception
services:
  nginx:
    build:
      context: requirements/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - 80:80
    volumes:
      - ./requirements/tools/website-files:/var/www/html
  wordpress:
    build:
      context: requirements/wordpress
    container_name: wordpress
    tty: true
    restart: always
    depends_on: [ 'mysql' ]
    volumes:
      - ./requirements/tools/website-files:/var/www/html/
  mysql:
    build:
      context: requirements/mariadb
    container_name: mariadb
    tty: true
    restart: always
    environment:
      MYSQL_DATABASE: wp
    env_file:
      - .env
      # - ./tools:/etc/
      # volumes:
      #   wordpress-website-volume:
      #   wordpress-database-volume:
      # secrets:
      #   db-password:
      #     file: srcs/requirements/mariadb/conf/password.txt

