version: "3.9"
name: inception
services:
  nginx:
    build:
      dockerfile: ./nginx/Dockerfile
      context: requirements/
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - frontend
    volumes:
      - ./requirements/tools/website-files:/var/www/html
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    tty: true
    ports:
      - 9000:9000
    volumes:
      - ./requirements/tools/website-files:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy

    links:
      - mariadb
    env_file:
      - .env
    networks:
      - frontend
      - backend
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    volumes:
      - ./requirements/tools/db:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mariadb",
          "-h$MYSQL_HOST",
          "-u$WP_DATABASE_USR",
          "-p$WP_DATABASE_PWD",
          "$WP_DATABASE_NAME"
        ]
      interval: 1s
      retries: 3
      start_period: 30s
    networks:
      - backend
    env_file:
      - .env
networks:
  frontend:
  backend:
