version: "3.9"
name: inception
services:
  nginx:
    build:
      dockerfile: ./nginx/Dockerfile
      context: requirements/
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - frontend
    volumes:
      - ./requirements/tools/website-files:/var/www/html
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    tty: true
    ports:
      - 9000:9000
    volumes:
      - ./requirements/tools/website-files:/var/www/html
    depends_on:
      - mariadb
    # links:
    #   - mariadb
    environment:
      # WORDPRESS_DB_HOST: mariadb:3260
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: secret
    networks:
      - frontend
      - backend
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    volumes:
      - ./requirements/tools/db:/var/lib/mysql
    ports:
      - "3306:3306"
    tty: true
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - backend
    # env_file:
    #   - .env
networks:
  frontend:
  backend:
