name: inception
services:
  nginx:
    build:
      context: requirements/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - 80:80
    #   networks:
    #     - private
  wordpress:
    build:
      context: requirements/wordpress
    container_name: wordpress
    tty: true
    depends_on: [ 'mysql' ]
    #     networks:
    #       - private
    #     restart: always
    # ports: ['8000:80']
    # networks:
    #   private:
    volumes:
      - ../tools/website-files:/wordpress-files
  mysql:
    build:
      context: requirements/mariadb
    container_name: mariadb
    tty: true
    environment:
      MYSQL_DATABASE: wp
    env_file:
      - .env
    volumes:
      - ./tools:/etc/
    # volumes:
    #   wordpress-website-volume:
    #   wordpress-database-volume:
    # secrets:
    #   db-password:
    #     file: srcs/requirements/mariadb/conf/password.txt

