version: "3.9"
name: inception
services:
  nginx:
    build:
      dockerfile: ./nginx/Dockerfile
      context: requirements/
    container_name: nginx
    init: true
    restart: always
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - frontend
    extra_hosts:
      - "$DOMAIN_NAME:127.0.0.1"
    volumes:
      - wordpress_data:/var/www/html
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    init: true
    restart: always
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    extra_hosts:
      - "$DOMAIN_NAME:127.0.0.1"
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    init: true
    restart: always
    networks:
      - backend
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
networks:
  frontend:
  backend:

volumes:
  mariadb_data:
    driver: local
    name: mariadb_data
    driver_opts:
      device: /home/ngasco/data/db
  wordpress_data:
    name: wordpress_data
    driver_opts:
      device: /home/ngasco/data/website-files