version: "3.9"
name: inception
services:
  nginx:
    build:
      dockerfile: ./nginx/Dockerfile
      context: requirements/
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - frontend
    volumes:
      - /Users/dev/Documents/42_cursus/17_inception/website-files:/var/www/html
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    ports:
      - 9000:9000
    networks:
      - frontend
      - backend
    volumes:
      - /Users/dev/Documents/42_cursus/17_inception/website-files:/var/www/html
    env_file:
      - .env
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - /Users/dev/Documents/42_cursus/17_inception/db:/var/lib/mysql
    env_file:
      - .env
networks:
  frontend:
  backend:
