name: inception
services:
  nginx:
    build:
      context: requirements/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:43"
    depends_on: [ 'wordpress' ]
    #   networks:
    #     - private
  wordpress:
    build:
      context: requirements/wordpress
    container_name: wordpress
    tty: true
    #     networks:
    #       - private
    #     restart: always
    # ports: ['8000:80']
    # networks:
    #   private:
volumes:
  wordpress-website-volume:
  wordpress-database-volume:
    # secrets:
    #   db-password:
    #     file: srcs/requirements/mariadb/conf/password.txt

