version: "3.9"
name: inception
services:
  nginx:
    build:
      dockerfile: ./nginx/Dockerfile
      context: requirements/
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    # depends_on:
    #   - wordpress
    ports:
      - "80:80"
    networks:
      - frontend
    volumes:
      - ./requirements/nginx/conf/index.html:/usr/share/nginx/html/index.html
    # wordpress:
    #   build:
    #     context: requirements/wordpress
    #   container_name: wordpress
    #   tty: true
    #   restart: always
    #   depends_on:
    #     - mariadb
    #   ports:
    #     - "9000:9000"
    #   volumes:
    #     - ./requirements/tools/website-files:/var/www/html
    # networks:
    #   - frontend
    #   - backend
    # mariadb:
    #   build:
    #     context: requirements/mariadb
    #   container_name: mariadb
    #   tty: true
    #   restart: always
    #   volumes:
    #     - ./requirements/tools/db:/var/lib/mysql
    #   ports:
    #     - "3306:3306"
    #   environment:
    #     MYSQL_DATABASE: wp
    #   env_file:
    #     - .env
    # networks:
    #   - backend
networks:
  frontend:
  backend:


