version: '1'
services:
  nginx:
    build:
      context: srcs/requirements/nginx
    restart: always
    tty: true
    # ports:
    #   - "443"
    #   networks:
    #     - private
  wordpress:
    build:
      context: srcs/requirements/wordpress
    tty: true
    depends_on:
      - nginx
    networks:
      - private
    restart: always
networks:
  private:
volumes:
  wordpress-website-volume:
  wordpress-database-volume:
    # secrets:
    #   db-password:
    #     file: srcs/requirements/mariadb/conf/password.txt
