services:
  python:
    container_name: "learn2slither"
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/learn2slither
    environment:
      - CONSTANTS_DIR_PATH=/learn2slither/constants/
      - MAPS_DIR_PATH=/learn2slither/maps/
      - SETTINGS_DIR_PATH=/learn2slither/settings/
