services:
  python:
    container_name: "learn2slither"
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/learn2slither
    environment:
      - SETTINGS_DIR_PATH=/learn2slither/settings/
